Repository AY2223S1-CS2103T-W15-4/tp, pull requests merged in 2022-11, with the labels that each got.

#178 Alias bug fix
  src/main/java/friday/logic/commands/AliasCommand.java
  src/main/java/friday/model/alias/Alias.java
  src/main/java/friday/storage/JsonSerializableFriday.java
Labels: type.BugFix, priority.High

#180 User guide
  docs/UserGuide.md
Labels: documentation, type.BugFix

#177 Update UG to fix bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/Startup.png
  docs/index.md
  docs/team/johndoe.md
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/test/java/friday/testutil/StudentUtil.java
Labels: documentation, type.BugFix

#181 Refactor docs
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/tutorials/TracingCode.md
  src/test/java/friday/storage/JsonSerializableFridayTest.java
  src/test/java/friday/storage/JsonUserPrefsStorageTest.java
Labels: documentation

#179 Update DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortCommandActivityDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/AddCommand.png
  docs/images/AddCommandOutcome.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SortCommandActivityDiagram.png
  docs/images/SortCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoSequenceDiagram.png
  docs/tutorials/TracingCode.md
  src/main/java/friday/model/util/SampleDataUtil.java
  src/main/resources/images/friday_logo.png
  src/test/java/friday/storage/JsonSerializableMasteryCheckBookTest.java
  src/test/java/friday/testutil/FridayBuilder.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: documentation, priority.High

#182 Update GradeCommand in DG
  docs/DeveloperGuide.md
  docs/diagrams/GradeSequenceDiagram.puml
  docs/images/GradeSequenceDiagram.png
  src/main/java/friday/logic/commands/RemarkCommand.java
  src/main/java/friday/logic/parser/RemarkCommandParser.java
  src/main/java/friday/model/student/Remark.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/logic/parser/FridayParserTest.java
  src/test/java/friday/logic/parser/RemarkCommandParserTest.java
  src/test/java/friday/model/student/RemarkTest.java
Labels: documentation

#184 Fix UG bug
  docs/UserGuide.md
  src/main/resources/images/friday_logo.png
Labels: documentation, type.BugFix

#183 Update find command tests
  src/test/data/JsonSerializableFridayTest/duplicateStudentFriday.json
  src/test/data/JsonSerializableFridayTest/invalidStudentFriday.json
  src/test/data/JsonSerializableFridayTest/typicalStudentFriday.json
  src/test/java/friday/logic/LogicManagerTest.java
  src/test/java/friday/logic/commands/FindCommandTest.java
  src/test/java/friday/model/student/UniqueStudentListTest.java
  src/test/java/friday/storage/JsonFridayStorageTest.java
  src/test/java/friday/storage/JsonSerializableFridayTest.java
  src/test/java/friday/storage/JsonSerializableMasteryCheckBookTest.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: type.Task

#186 Add GradesListTest
  docs/team/howsuen.md
  src/main/java/friday/model/grades/GradesList.java
  src/test/java/friday/logic/commands/GradeCommandTest.java
  src/test/java/friday/model/grade/GradeTest.java
  src/test/java/friday/model/grade/GradesListTest.java
Labels: type.Task, priority.High

#187 Fix bug where more than 1 Mastery Check is marked in the same command
  src/main/java/friday/logic/commands/MarkMasteryCheckCommand.java
  src/main/java/friday/logic/commands/UnmarkMasteryCheckCommand.java
  src/main/java/friday/model/student/MasteryCheck.java
Labels: type.BugFix, priority.High

#185 Add more test cases in AliasTest for isValidAlias
  src/test/java/friday/model/alias/AliasTest.java
Labels: type.Task, priority.Medium

#188 Improve UGDG and code quality
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/AddCommandOutcome.png
  docs/images/SortCommand.png
  docs/images/SortCommandOutcome.png
  docs/images/SortCommandSequenceDiagram.png
  docs/images/Startup.png
  docs/images/Ui.png
  docs/images/jorrdansoh.png
  docs/team/johndoe.md
  docs/team/jorrdansoh.md
  docs/tutorials/TracingCode.md
  src/main/java/friday/logic/Logic.java
  src/main/java/friday/logic/commands/AddCommand.java
  src/main/java/friday/logic/commands/SortCommand.java
  src/main/java/friday/logic/parser/Prefix.java
  src/main/java/friday/logic/parser/SortCommandParser.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/student/Consultation.java
  src/main/java/friday/model/student/MasteryCheck.java
  src/main/java/friday/model/student/Name.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/main/java/friday/storage/JsonAdaptedStudent.java
  src/main/java/friday/ui/StudentListPanel.java
  src/test/java/friday/logic/LogicManagerTest.java
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/DeleteCommandTest.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/GradeCommandTest.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/model/FridayTest.java
  src/test/java/friday/model/ModelManagerTest.java
  src/test/java/friday/model/UserPrefsTest.java
  src/test/java/friday/model/student/ConsultationTest.java
  src/test/java/friday/model/student/MasteryCheckTest.java
  src/test/java/friday/model/student/TelegramHandleTest.java
  src/test/java/friday/storage/JsonSerializableFridayTest.java
Labels: documentation, type.Task, priority.High

#190 Add tests for mark and unmark commands
  src/main/java/friday/logic/commands/MarkMasteryCheckCommand.java
  src/main/java/friday/logic/commands/UnmarkMasteryCheckCommand.java
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/EditStudentDescriptorTest.java
  src/test/java/friday/logic/commands/MarkMasteryCheckCommandTest.java
  src/test/java/friday/logic/commands/UnmarkMasteryCheckCommandTest.java
  src/test/java/friday/logic/parser/EditCommandParserTest.java
  src/test/java/friday/model/FridayTest.java
  src/test/java/friday/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/friday/model/student/StudentTest.java
  src/test/java/friday/model/student/UniqueStudentListTest.java
  src/test/java/friday/testutil/StudentBuilder.java
  src/test/java/friday/testutil/TypicalIndexes.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: type.Task, priority.High

#189 Update UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCommandActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandOutcome.png
  docs/images/FindSequenceDiagram.png
  docs/team/yuvaraj0702.md
Labels: documentation

#191 Update UG and DG documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GradeCommandActivityDiagram.puml
  docs/diagrams/GradeSequenceDiagram.puml
  docs/images/EditCommandInitial.png
  docs/images/EditCommandOutcome.png
  docs/images/GradeCommand.png
  docs/images/GradeCommandActivityDiagram.png
  docs/images/GradeSequenceDiagram.png
  docs/images/RemarkCommandOutcome.png
  docs/team/howsuen.md
Labels: documentation, priority.High

#192 Documentation
  docs/DeveloperGuide.md
  docs/diagrams/AliasCommandActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UsingAliasSequenceDiagram.puml
  docs/images/AliasCommandActivityDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UsingAliasSequenceDiagram.png
  docs/team/darrtzj.md
Labels: documentation

#193 Update PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yuvaraj0702.md
Labels: documentation

#194 Update UG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jorrdansoh.md
Labels: documentation, type.Task, type.BugFix

#195 Edit UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MarkCommandActivityDiagram.puml
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/diagrams/UnmarkCommandActivityDiagram.puml
  docs/diagrams/UnmarkCommandSequenceDiagram.puml
  docs/images/MarkCommandActivityDiagram.png
  docs/images/MarkCommandBefore.png
  docs/images/MarkCommandOutcome.png
  docs/images/MarkCommandSequenceDiagram.png
  docs/images/UnmarkCommandActivityDiagram.png
  docs/images/UnmarkCommandBefore.png
  docs/images/UnmarkCommandOutcome.png
  docs/images/UnmarkCommandSequenceDiagram.png
Labels: documentation, type.Task, priority.High

#197 Ugdg documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#198 Update documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/darrtzj.md
Labels: documentation

#199 Update about us
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FindCommandSequenceDiagram.png
Labels: documentation

#200 Edit UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UnmarkCommandActivityDiagram.puml
  docs/images/UnmarkCommandActivityDiagram.png
Labels: documentation, type.BugFix, priority.High

#202 Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: documentation

#203 Update base UG
  docs/UserGuide.md
Labels: documentation

#204 Add section descriptions and when each command will be useful
  docs/UserGuide.md
Labels: documentation, priority.High

#205 Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/howsuen.md
  docs/team/jorrdansoh.md
  docs/team/yuvaraj0702.md
Labels: documentation

#206 Update UG documentation
  docs/UserGuide.md
  docs/team/howsuen.md
Labels: documentation, priority.High

#207 Update UG
  docs/UserGuide.md
  docs/team/jorrdansoh.md
Labels: documentation, type.Task

#210 Documentation
  docs/UserGuide.md
  docs/images/layout.png
  docs/team/darrtzj.md
Labels: documentation

#211 Edit UG and PPP
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/kaij77.md
Labels: documentation, priority.High

#214 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#215 Update UG for add and sort
  docs/UserGuide.md
Labels: documentation, type.Task

#213 Ugdg documentation
  docs/UserGuide.md
  docs/images/EditCommandInitial.png
  docs/images/EditCommandOutcome.png
  docs/images/MarkCommandBefore.png
  docs/images/MarkCommandOutcome.png
  docs/images/SortCommand.png
  docs/images/SortCommandOutcome.png
  docs/images/UnmarkCommandBefore.png
  docs/images/UnmarkCommandOutcome.png
Labels: documentation, type.BugFix, priority.High

#218 Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#222 Update DG
  docs/DeveloperGuide.md
  docs/images/FindCommandActivityDiagram.png
  docs/images/FindCommandSequenceDiagram.png
Labels: documentation, priority.High

#225 Update Command Parameters table in UG
  docs/UserGuide.md
Labels: documentation

#224 Edit UG for CS2101
  docs/UserGuide.md
Labels: documentation, priority.High

#227 Update UG for cs2101
  docs/UserGuide.md
Labels: documentation

#230 Ugdg documentation
  docs/UserGuide.md
Labels: documentation

#228 Update UG for add, delete and sort
  docs/UserGuide.md
Labels: documentation

#231 Documentation
  docs/UserGuide.md
Labels: documentation

#232 Edit UG for CS2101
  docs/UserGuide.md
  docs/images/ClearCommandOutcome.png
  docs/images/GuideCommandOutcome.png
  docs/images/HelpCommandOutcome.png
Labels: documentation, priority.High

#233 Edit UG for CS2101
  docs/UserGuide.md
  docs/images/HelpCommandOutcome.png
Labels: documentation, priority.High

#234 UG
  docs/UserGuide.md
Labels: documentation, priority.High
