Repository AY2223S1-CS2103T-W15-4/tp, pull requests merged in 2022-10, with the labels that each got.

#81 11 help command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Medium

#82 Update findcommand
  src/main/java/friday/logic/commands/FindCommand.java
Labels: documentation, priority.High

#83 Update AddCommand
  docs/UserGuide.md
  src/main/java/friday/logic/commands/AddCommand.java
  src/main/java/friday/logic/parser/DeleteCommandParser.java
Labels: documentation

#85 Refactor to friday
  src/main/java/friday/MainApp.java
  src/main/java/friday/logic/Logic.java
  src/main/java/friday/logic/LogicManager.java
  src/main/java/friday/logic/commands/ClearCommand.java
  src/main/java/friday/model/Friday.java
  src/main/java/friday/model/Model.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/ReadOnlyFriday.java
  src/main/java/friday/model/util/SampleDataUtil.java
  src/main/java/friday/storage/AddressBookStorage.java
  src/main/java/friday/storage/JsonAddressBookStorage.java
  src/main/java/friday/storage/JsonSerializableAddressBook.java
  src/main/java/friday/storage/Storage.java
  src/main/java/friday/storage/StorageManager.java
  src/test/java/friday/logic/LogicManagerTest.java
  src/test/java/friday/logic/commands/AddCommandIntegrationTest.java
  src/test/java/friday/logic/commands/AddCommandTest.java
  src/test/java/friday/logic/commands/ClearCommandTest.java
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/DeleteCommandTest.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/ListCommandTest.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/model/MasteryCheckBookTest.java
  src/test/java/friday/model/ModelManagerTest.java
  src/test/java/friday/storage/JsonMasteryCheckBookStorageTest.java
  src/test/java/friday/storage/StorageManagerTest.java
  src/test/java/friday/testutil/AddressBookBuilder.java
  src/test/java/friday/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#87 Update ability to add students given name and Telegram handle
  docs/UserGuide.md
  docs/team/jorrdansoh.md
  src/main/java/friday/logic/LogicManager.java
  src/main/java/friday/logic/commands/AddCommand.java
  src/main/java/friday/logic/commands/DeleteCommand.java
  src/main/java/friday/logic/commands/EditCommand.java
  src/main/java/friday/logic/commands/FindCommand.java
  src/main/java/friday/logic/commands/ListCommand.java
  src/main/java/friday/logic/commands/RemarkCommand.java
  src/main/java/friday/logic/parser/AddCommandParser.java
  src/main/java/friday/logic/parser/CliSyntax.java
  src/main/java/friday/logic/parser/EditCommandParser.java
  src/main/java/friday/logic/parser/ParserUtil.java
  src/main/java/friday/model/Model.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/student/Consultation.java
  src/main/java/friday/model/student/MasteryCheck.java
  src/main/java/friday/model/student/Remark.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/main/java/friday/model/student/UniquePersonList.java
  src/main/java/friday/model/util/SampleDataUtil.java
  src/test/java/friday/logic/LogicManagerTest.java
  src/test/java/friday/logic/commands/AddCommandIntegrationTest.java
  src/test/java/friday/logic/commands/AddCommandTest.java
  src/test/java/friday/logic/commands/ClearCommandTest.java
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/DeleteCommandTest.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/FindCommandTest.java
  src/test/java/friday/logic/commands/ListCommandTest.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/logic/parser/AddCommandParserTest.java
  src/test/java/friday/logic/parser/ParserUtilTest.java
  src/test/java/friday/model/MasteryCheckBookTest.java
  src/test/java/friday/model/ModelManagerTest.java
  src/test/java/friday/model/student/ConsultationTest.java
  src/test/java/friday/model/student/MasteryCheckTest.java
  src/test/java/friday/model/student/StudentTest.java
  src/test/java/friday/model/student/TelegramHandleTest.java
  src/test/java/friday/model/student/UniqueStudentListTest.java
  src/test/java/friday/storage/JsonAdaptedStudentTest.java
  src/test/java/friday/storage/JsonMasteryCheckBookStorageTest.java
  src/test/java/friday/storage/JsonSerializableMasteryCheckBookTest.java
  src/test/java/friday/storage/StorageManagerTest.java
  src/test/java/friday/testutil/TestUtil.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: priority.High

#88 Change to match naming convention
  docs/DeveloperGuide.md
Labels: documentation

#89 Add Edit Command tests
  docs/team/howsuen.md
  src/main/java/friday/logic/commands/EditCommand.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/parser/EditCommandParserTest.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: type.Task, priority.High

#92 Modify dummy values and fix AY2223S1-CS2103T-W15-4/tp#91
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/team/jorrdansoh.md
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/friday/MainApp.java
  src/main/java/friday/logic/commands/ClearCommand.java
  src/main/java/friday/logic/commands/ExitCommand.java
  src/main/java/friday/logic/parser/AddCommandParser.java
  src/main/java/friday/logic/parser/EditCommandParser.java
  src/main/java/friday/logic/parser/ParserUtil.java
  src/main/java/friday/model/student/Consultation.java
  src/main/java/friday/model/student/MasteryCheck.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/main/java/friday/storage/JsonAdaptedPerson.java
  src/test/java/friday/logic/parser/ParserUtilTest.java
  src/test/java/friday/model/student/ConsultationTest.java
  src/test/java/friday/model/student/MasteryCheckTest.java
  src/test/java/friday/model/student/TelegramHandleTest.java
  src/test/java/friday/storage/JsonAdaptedStudentTest.java
Labels: type.BugFix, priority.High

#93 Add find individual student details functionality
  docs/UserGuide.md
  src/main/java/friday/model/student/NameContainsKeywordsPredicate.java
Labels: priority.High

#96 Edit sample data's remarks and tags
  src/main/java/friday/model/student/Consultation.java
  src/main/java/friday/model/student/MasteryCheck.java
  src/main/java/friday/model/tag/Tag.java
  src/main/java/friday/model/util/SampleDataUtil.java
  src/main/java/friday/ui/PersonCard.java
  src/test/java/friday/logic/parser/EditCommandParserTest.java
  src/test/java/friday/model/tag/TagTest.java
Labels: type.BugFix, priority.Medium

#100 11 help command
  docs/UserGuide.md
  src/main/java/friday/ui/HelpWindow.java
Labels: documentation, type.Task

#101 Update GUI logo and title and TelegramHandle and refactor files
  docs/UserGuide.md
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/team/howsuen.md
  docs/tutorials/TracingCode.md
  src/main/java/friday/logic/commands/EditCommand.java
  src/main/java/friday/logic/parser/EditCommandParser.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/main/java/friday/ui/UiManager.java
  src/main/resources/images/friday_logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/friday/commons/util/AppUtilTest.java
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/EditStudentDescriptorTest.java
  src/test/java/friday/logic/parser/EditCommandParserTest.java
  src/test/java/friday/logic/parser/MasteryCheckBookParserTest.java
  src/test/java/friday/model/student/TelegramHandleTest.java
  src/test/java/friday/testutil/EditPersonDescriptorBuilder.java
  src/test/java/friday/testutil/EditStudentDescriptorBuilder.java
  src/test/java/friday/testutil/PersonUtil.java
Labels: documentation, type.Enhancement, type.Task, priority.High

#103 Change colour of GUI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, type.Task

#102 Make string containing the link to the User Guide static
  src/main/java/friday/logic/commands/UgCommand.java
Labels: type.BugFix, priority.High

#104 Enable assertions when running FRIDAY
  build.gradle
Labels: priority.High

#105 Update DeveloperGuide.md with the Alias feature
  docs/DeveloperGuide.md
Labels: documentation

#107 Update DG and UG for sort feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jorrdansoh.md
  src/main/java/friday/MainApp.java
Labels: documentation

#110 Update dg and change file names
  docs/DeveloperGuide.md
  src/main/java/friday/model/Friday.java
  src/main/java/friday/model/student/UniqueStudentList.java
  src/main/java/friday/storage/JsonAdaptedStudent.java
  src/main/java/friday/storage/JsonSerializableFriday.java
  src/test/java/friday/model/student/UniqueStudentListTest.java
  src/test/java/friday/storage/JsonAdaptedStudentTest.java
Labels: priority.High

#113 Add assertions
  src/main/java/friday/logic/commands/FindCommand.java
Labels: priority.Low

#115 Refactor MasteryCheckBook to Friday
  src/main/java/friday/storage/JsonAdaptedStudent.java
  src/test/java/friday/logic/parser/FridayParserTest.java
  src/test/java/friday/storage/JsonFridayStorageTest.java
  src/test/java/friday/storage/JsonSerializableFridayTest.java
  src/test/java/friday/storage/StorageManagerTest.java
Labels: type.BugFix, priority.High

#116 Add functionality to edit students' grades
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/howsuen.md
  src/main/java/friday/logic/commands/EditCommand.java
  src/main/java/friday/logic/commands/GradeCommand.java
  src/main/java/friday/logic/commands/RemarkCommand.java
  src/main/java/friday/logic/parser/AddCommandParser.java
  src/main/java/friday/logic/parser/CliSyntax.java
  src/main/java/friday/logic/parser/FridayParser.java
  src/main/java/friday/logic/parser/GradeCommandParser.java
  src/main/java/friday/logic/parser/ParserUtil.java
  src/main/java/friday/model/grades/Grade.java
  src/main/java/friday/model/grades/GradesList.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/model/util/SampleDataUtil.java
  src/main/java/friday/storage/JsonAdaptedGrade.java
  src/main/java/friday/storage/JsonAdaptedStudent.java
  src/main/java/friday/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/friday/logic/commands/CommandTestUtil.java
  src/test/java/friday/logic/commands/GradeCommandTest.java
  src/test/java/friday/logic/parser/FridayParserTest.java
  src/test/java/friday/logic/parser/GradeCommandParserTest.java
  src/test/java/friday/model/grade/GradeTest.java
  src/test/java/friday/storage/JsonAdaptedStudentTest.java
  src/test/java/friday/testutil/EditGradeDescriptorBuilder.java
  src/test/java/friday/testutil/StudentBuilder.java
  src/test/java/friday/testutil/StudentUtil.java
Labels: documentation, type.Story, priority.High

#118 Add alias feature
  src/main/java/friday/logic/LogicManager.java
  src/main/java/friday/logic/commands/AliasCommand.java
  src/main/java/friday/logic/commands/AliasListCommand.java
  src/main/java/friday/logic/commands/UnaliasCommand.java
  src/main/java/friday/logic/parser/AliasCommandParser.java
  src/main/java/friday/logic/parser/CliSyntax.java
  src/main/java/friday/logic/parser/FridayParser.java
  src/main/java/friday/logic/parser/ParserUtil.java
  src/main/java/friday/logic/parser/UnaliasCommandParser.java
  src/main/java/friday/model/Friday.java
  src/main/java/friday/model/Model.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/ReadOnlyFriday.java
  src/main/java/friday/model/alias/Alias.java
  src/main/java/friday/model/alias/AliasMap.java
  src/main/java/friday/model/alias/ReservedKeyword.java
  src/main/java/friday/model/alias/exceptions/AliasNotFoundException.java
  src/main/java/friday/model/alias/exceptions/DuplicateAliasException.java
  src/main/java/friday/model/student/Remark.java
  src/main/java/friday/storage/JsonAdaptedAlias.java
  src/main/java/friday/storage/JsonSerializableFriday.java
  src/test/java/friday/logic/commands/AddCommandTest.java
  src/test/java/friday/logic/commands/AliasCommandTest.java
  src/test/java/friday/logic/commands/SortCommandTest.java
  src/test/java/friday/logic/commands/UnaliasCommandTest.java
  src/test/java/friday/logic/parser/AliasCommandParserTest.java
  src/test/java/friday/logic/parser/FridayParserTest.java
  src/test/java/friday/logic/parser/ParserUtilTest.java
  src/test/java/friday/logic/parser/UnaliasCommandParserTest.java
  src/test/java/friday/model/MasteryCheckBookTest.java
  src/test/java/friday/model/alias/AliasMapTest.java
  src/test/java/friday/model/alias/AliasTest.java
  src/test/java/friday/model/alias/ReservedKeywordTest.java
Labels: type.Task, priority.High

#117 Add find by other parameters
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/yuvaraj0702.md
  src/main/java/friday/MainApp.java
  src/main/java/friday/logic/commands/FindCommand.java
  src/main/java/friday/logic/commands/MarkMasteryCheckCommand.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/ReadOnlyUserPrefs.java
  src/main/java/friday/model/UserPrefs.java
  src/main/java/friday/model/student/NameContainsKeywordsPredicate.java
  src/main/java/friday/model/tag/Tag.java
  src/main/java/friday/model/util/SampleDataUtil.java
  src/main/java/friday/storage/JsonSerializableFriday.java
  src/test/java/friday/model/ModelManagerTest.java
  src/test/java/friday/model/UserPrefsTest.java
  src/test/java/friday/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/friday/storage/JsonUserPrefsStorageTest.java
  src/test/java/friday/testutil/AddressBookBuilder.java
  src/test/java/friday/testutil/FridayBuilder.java
Labels: priority.High

#121 Migrate find functionality to sort
  src/main/java/friday/logic/parser/SortCommandParser.java
Labels: priority.High

#120 Update User Guide and improve Order class
  docs/UserGuide.md
  docs/team/howsuen.md
  docs/team/jorrdansoh.md
  src/main/java/friday/logic/commands/GradeCommand.java
  src/main/java/friday/logic/parser/AddCommandParser.java
  src/main/java/friday/logic/parser/GradeCommandParser.java
  src/main/java/friday/logic/parser/Order.java
  src/main/java/friday/logic/parser/SortCommandParser.java
  src/main/java/friday/model/grades/GradesList.java
  src/main/java/friday/model/student/MasteryCheck.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/storage/JsonAdaptedGrade.java
  src/main/java/friday/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/friday/logic/commands/GradeCommandTest.java
  src/test/java/friday/testutil/EditGradeDescriptorBuilder.java
Labels: documentation, priority.High

#122 Update alias feature
  src/main/java/friday/logic/commands/AliasCommand.java
  src/main/java/friday/model/Friday.java
  src/main/java/friday/model/Model.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/ReadOnlyFriday.java
  src/main/java/friday/model/alias/Alias.java
  src/main/java/friday/model/alias/AliasMap.java
  src/main/java/friday/model/alias/ReservedKeyword.java
  src/main/java/friday/storage/JsonAdaptedAlias.java
  src/test/java/friday/logic/commands/AddCommandTest.java
  src/test/java/friday/logic/commands/AliasCommandTest.java
  src/test/java/friday/logic/commands/SortCommandTest.java
  src/test/java/friday/logic/parser/AliasCommandParserTest.java
  src/test/java/friday/logic/parser/UnaliasCommandParserTest.java
  src/test/java/friday/model/MasteryCheckBookTest.java
  src/test/java/friday/model/alias/AliasMapTest.java
  src/test/java/friday/model/alias/AliasTest.java
Labels: type.Task, priority.High

#123 Update HelpWindow
  src/main/java/friday/logic/parser/MarkMasteryCheckCommandParser.java
  src/main/java/friday/ui/HelpWindow.java
Labels: type.Bug, priority.High

#125 Add visuals in User Guide
  docs/UserGuide.md
  docs/images/AddCommand.png
  docs/images/AddCommandOutcome.png
  docs/images/SortCommand.png
  docs/images/SortCommandOutcome.png
  docs/team/jorrdansoh.md
  src/main/java/friday/MainApp.java
  src/main/java/friday/logic/parser/SortCommandParser.java
Labels: documentation, priority.High

#124 User guide
  docs/UserGuide.md
  docs/team/darrtzj.md
Labels: documentation, priority.High

#126 Update tests associated with find command
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/images/FindCommand.png
  docs/images/FindCommandOutcome.png
  docs/team/howsuen.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/main/java/friday/MainApp.java
  src/main/java/friday/logic/Logic.java
  src/main/java/friday/logic/LogicManager.java
  src/main/java/friday/logic/commands/FindCommand.java
  src/main/java/friday/logic/commands/SortCommand.java
  src/main/java/friday/model/ModelManager.java
  src/main/java/friday/model/tag/Tag.java
  src/main/java/friday/storage/JsonSerializableFriday.java
  src/main/java/friday/ui/MainWindow.java
  src/test/data/JsonFridayStorageTest/invalidAndValidStudentFriday.json
  src/test/data/JsonFridayStorageTest/invalidStudentFriday.json
  src/test/data/JsonFridayStorageTest/notJsonFormatFriday.json
  src/test/data/JsonSerializableFridayTest/duplicateStudentFriday.json
  src/test/data/JsonSerializableFridayTest/invalidStudentFriday.json
  src/test/data/JsonSerializableFridayTest/typicalStudentFriday.json
  src/test/java/friday/logic/commands/AddCommandIntegrationTest.java
  src/test/java/friday/logic/commands/AliasCommandTest.java
  src/test/java/friday/logic/commands/ClearCommandTest.java
  src/test/java/friday/logic/commands/DeleteCommandTest.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/FindCommandTest.java
  src/test/java/friday/logic/commands/GradeCommandTest.java
  src/test/java/friday/logic/commands/ListCommandTest.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/logic/commands/UnaliasCommandTest.java
  src/test/java/friday/model/MasteryCheckBookTest.java
  src/test/java/friday/storage/JsonFridayStorageTest.java
  src/test/java/friday/storage/StorageManagerTest.java
  src/test/java/friday/testutil/TypicalStudents.java
Labels: type.BugFix

#127 Simplify ORDER syntax in sort command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SortCommand.png
  src/main/java/friday/logic/parser/CliSyntax.java
  src/main/java/friday/logic/parser/Order.java
Labels: priority.High

#129 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/GradeCommand.png
  docs/images/Ui.png
  docs/team/howsuen.md
  src/test/java/friday/model/grade/GradeTest.java
Labels: documentation

#130 Fix UI bug in MarkMasteryCheckCommand and UnmarkMasteryCheckCommand
  src/main/java/friday/logic/commands/MarkMasteryCheckCommand.java
  src/main/java/friday/logic/commands/UnmarkMasteryCheckCommand.java
  src/main/java/friday/model/alias/ReservedKeyword.java
  src/main/java/friday/ui/StudentListPanel.java
Labels: type.BugFix, priority.High

#131 Update FRIDAY version to v1.3.1
  src/main/java/friday/MainApp.java
  src/main/java/friday/commons/core/LogsCenter.java
Labels: type.Task, priority.High

#134 Fix #132 and tidy up Developer Guide
  docs/DeveloperGuide.md
  src/main/java/friday/logic/parser/ParserUtil.java
  src/main/java/friday/model/student/Consultation.java
  src/main/java/friday/model/student/MasteryCheck.java
Labels: documentation, type.BugFix, priority.High

#135 Add images of Mark and UnmarkMasteryCheckCommand to UG
  docs/UserGuide.md
  docs/images/MarkCommandOutcome.png
  docs/images/UnmarkCommandOutcome.png
Labels: documentation, priority.High

#163 Fix edge case sorting bug
  src/main/java/friday/logic/parser/SortCommandParser.java
Labels: type.BugFix, priority.High

#172 Fix bugs from PE-D
  docs/UserGuide.md
  src/main/java/friday/logic/commands/EditCommand.java
  src/main/java/friday/model/grades/Grade.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/main/java/friday/model/tag/Tag.java
  src/test/java/friday/model/grade/GradeTest.java
Labels: type.BugFix, severity.Medium

#173 Update user guide
  docs/UserGuide.md
Labels: documentation, type.BugFix

#171 Fix reported PE-D bugs
  docs/team/jorrdansoh.md
  src/main/java/friday/model/student/Name.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/model/student/TelegramHandle.java
  src/test/java/friday/model/student/NameTest.java
  src/test/java/friday/model/student/StudentTest.java
  src/test/java/friday/model/student/TelegramHandleTest.java
Labels: type.BugFix, priority.High

#174 Improve code quality
  src/main/java/friday/logic/commands/AddCommand.java
  src/main/java/friday/logic/commands/EditCommand.java
  src/main/java/friday/logic/commands/GradeCommand.java
  src/main/java/friday/logic/commands/RemarkCommand.java
  src/main/java/friday/logic/parser/ArgumentMultimap.java
  src/main/java/friday/logic/parser/SortCommandParser.java
  src/main/java/friday/model/grades/Grade.java
  src/main/java/friday/model/grades/GradesList.java
  src/main/java/friday/model/student/NameContainsKeywordsPredicate.java
  src/main/java/friday/model/student/Student.java
  src/main/java/friday/storage/JsonAdaptedGrade.java
  src/main/java/friday/ui/StudentCard.java
  src/test/java/friday/logic/commands/EditCommandTest.java
  src/test/java/friday/logic/commands/RemarkCommandTest.java
  src/test/java/friday/model/grade/GradeTest.java
  src/test/java/friday/testutil/StudentUtil.java
Labels: priority.High

#175 Fix bug where text is not fully shown under normal usage
  src/main/resources/view/StudentListCard.fxml
Labels: type.Bug, severity.Medium

#176 Fix bugs reported in PE-D
  docs/UserGuide.md
  src/main/java/friday/logic/commands/MarkMasteryCheckCommand.java
  src/main/java/friday/model/student/MasteryCheck.java
Labels: type.BugFix, priority.High
